php:
  build: .
  volumes:
    - .:/var/crackingCode
  environment:
    XDEBUG_CONFIG: remote_host={{192.168.1.14}}
composer:
  restart: 'no'
  image: composer/composer:php7
  command: install
  volumes:
    - .:/app